name: Local model build Test for linux/amd64 and linux/arm64

on:
  push: 
    branches: ['main']
  workflow_dispatch:
  
jobs:
  test_linux_amd64_and_amr64_build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'local test')
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Checkout persist credentials
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwises, you will failed to push refs to dest repo
  
      - name: Generate the Dockerfile
        id: generate-dockerfile
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_URL: "https://github.com/${{ github.repository }}"
        run: |
          wget https://raw.githubusercontent.com/emmakodes/checkbuild/main/local_place_a_dockerfile_in_current_eos_repo.py
          python -m pip install requests
          python local_place_a_dockerfile_in_current_eos_repo.py $REPO_NAME $REPO_URL    

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: build_test_dockerfile
